CONFIG_ARA=y # make system analyzable
CONFIG_KSCAN_EC=n # ARA: undefined reference to `keymap_init_interface'

CONFIG_NO_OPTIMIZATIONS=y # need O0 for analysis
CONFIG_SCHED_DUMB=y # only this is supported by SSE
CONFIG_STACK_SENTINEL=n # dont check sentinels on syscalls for SSE
